apiVersion: v1
kind: Service
metadata:
  name: themis-executor
  namespace: themis-executor
spec:
  selector:
    app: themis-executor
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 32137
