apiVersion: v1
kind: Service
metadata:
  name: zeuspol
  namespace: zeuspol
spec:
  selector:
    app: zeuspol
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 8085
      targetPort: 8085
      nodePort: 31111
